<?php

/* A. Prompts for the Survey and Vignettes
 * 
 * Based on the language selected in the new_welcome page, the appropiate
 * texts for survey and vignette prompts from dictionaries.php is used
 */ 
$prompts = $Survey_Prompts_Displayed; // survey prompts to be displayed
$vig_prompts = $Vignette_Prompts_Displayed;   // prompts specific to Vignettes


/* B. Vignettes Text
 * 
 * The texts for the vignettes are generated by an algorithm in "generate.py"
 * The generated text is passed from python to mysql. (Consider using json to get text as an array in php from Python?)
 * This section will read the Vignette text from mysql database
 * 
 * Also read the vignette text and responses from all previous Vignettes.  
 * These will be optional displays for the users.
 *  
 * Workflow: PYTHON (generate.py) ----generated text ----> MYSQL DATABASE ----generated text----> PHP (showVignetteX.php)
 */
 
 $result_order = sqlRowSelect('USA_vignettes_order_2017', "vig2LabourName1, vig2LabourID1, vig2LabourName2, vig2LabourID2, vig2HealthName1, vig2HealthID1, vig2HealthName2, vig2HealthID2, vig2HealthName3, vig2HealthID3, vig2SocialName1, vig2SocialID1, vig2SocialName2, vig2SocialID2, vig2SocialName3, vig2SocialID3, vig2SocialName4, vig2SocialID4, vig2SocialName5, vig2SocialID5, vig2CatOrder1, vig2CatOrder2, vig2CatOrder3", $_POST['ID']);      
 $row_order = mysqli_fetch_assoc($result_order);
 
 
 $result_text = sqlRowSelect('USA_vignettes_2017', "Vignette5Text, Vignette4Text, Vignette3Text, Vignette2Text, Vignette1Text, Vignette2TextLabour, Vignette2TextHealth, Vignette2TextSoc, Partner_Bool_2, Trust_Bool_2", $_POST['ID']);      
 $row_text = mysqli_fetch_assoc($result_text);
 
 
 $result_ans = sqlRowSelect('USA_responses_2017', "Vignette5Answer, Vignette4Answer, Vignette3Answer, Vignette2Answer, Vignette1Answer", $_POST['ID']);  
 $row_ans = mysqli_fetch_assoc($result_ans);
 
 
 
 // Full Vignette text
 $Vignette5Displayed= $row_text['Vignette5Text'];  //read Vignette 5 Text from mysql database
 $Vignette4Displayed= $row_text['Vignette4Text'];  //read Vignette 4 Text from mysql database
 $Vignette3Displayed= $row_text['Vignette3Text'];  //read Vignette 3 Text from mysql database
 $Vignette2Displayed= $row_text['Vignette2Text'];  //read Vignette 2 Text from mysql database
 $Vignette1Displayed= $row_text['Vignette1Text'];  //read Vignette 1 Text from mysql database
 
 // Vignette 2 Text by domain and order
 $Vignette2TextLabour = $row_text['Vignette2TextLabour'];
 $Vignette2TextHealth = $row_text['Vignette2TextHealth'];
 $Vignette2TextSoc = $row_text['Vignette2TextSoc'];
 
 
 $vig2CatOrder1 = $row_order['vig2CatOrder1'];
 $vig2CatOrder2 = $row_order['vig2CatOrder2'];
 $vig2CatOrder3 = $row_order['vig2CatOrder3'];
 
 $vig2Order = array($vig2CatOrder1, $vig2CatOrder2, $vig2CatOrder3);
 
 $vig2LabourName1 = $row_order['vig2LabourName1'];
 $vig2LabourID1 = $row_order['vig2LabourID1'];
 $vig2LabourName2 = $row_order['vig2LabourName2'];
 $vig2LabourID2 = $row_order['vig2LabourID2'];
 $vig2HealthName1 = $row_order['vig2HealthName1'];
 $vig2HealthID1 = $row_order['vig2HealthID1'];
 $vig2HealthName2 = $row_order['vig2HealthName2'];
 $vig2HealthID2 = $row_order['vig2HealthID2'];
 $vig2HealthName3 = $row_order['vig2HealthName3'];
 $vig2HealthID3 = $row_order['vig2HealthID3'];
 $vig2SocialName1 = $row_order['vig2SocialName1'];
 $vig2SocialID1 = $row_order['vig2SocialID1'];
 $vig2SocialName2 = $row_order['vig2SocialName2'];
 $vig2SocialID2 = $row_order['vig2SocialID2'];
 $vig2SocialName3 = $row_order['vig2SocialName3'];
 $vig2SocialID3 = $row_order['vig2SocialID3'];
 $vig2SocialName4 = $row_order['vig2SocialName4'];
 $vig2SocialID4 = $row_order['vig2SocialID4'];
 $vig2SocialName5 = $row_order['vig2SocialName5'];
 $vig2SocialID5 = $row_order['vig2SocialID5'];
 
 
 // Boolean for living with partner/trust
 $vig2PartnerBool = $row_text['Partner_Bool_2'];
 $vig2TrustBool = $row_text['Trust_Bool_2'];
 


//Vignette Response
 $vignette5Answer= $row_ans['Vignette5Answer'];  //read Vignette 5 Answer from mysql database
 $vignette4Answer= $row_ans['Vignette4Answer'];  //read Vignette 4 Answer from mysql database
 $vignette3Answer= $row_ans['Vignette3Answer'];  //read Vignette 3 Answer from mysql database
 $vignette2Answer= $row_ans['Vignette2Answer'];  //read Vignette 2 Answer from mysql database
 $vignette1Answer= $row_ans['Vignette1Answer'];  //read Vignette 1 Answer from mysql database
 
 
 // Get abs domain parameters to be displayed on Vignette 2
 $result_abs = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Val_2, Hours_Worked_Val_2, BMI_Val_2, BMI_Cat_2, Pain_Cat_2, Phys_Cat_2, Phys_Val_2, NumFrds_Val_2, FreqFrds_Cat_2, NumOrg_Val_2", $_POST['ID']);  
 
 $row_abs = mysqli_fetch_assoc($result_abs);
 
 $income_Val2 = number_format($row_abs['HouseHold_Income_Val_2']);
 $hoursWorked_Val2 = round($row_abs['Hours_Worked_Val_2']);
 $BMI_Val2 = round($row_abs['BMI_Val_2']);
 $BMI_Cat2 = $row_abs['BMI_Cat_2'];
 $pain_Cat2 = $row_abs['Pain_Cat_2'];
 $phys_Cat2 = $row_abs['Phys_Cat_2'];
 $phys_Val2 = round($row_abs['Phys_Val_2']);
 $numFrds_Val2 = round($row_abs['NumFrds_Val_2']);
 $freqFrds_Cat2 = $row_abs['FreqFrds_Cat_2'];
 $numOrg_Val2 = round($row_abs['NumOrg_Val_2']);
 
 $strFreqFrdRarely = "rarely and did not make any contact in the past month";
 $freqFrds_Val2 = strcmp($strFreqFrdRarely, $freqFrds_Cat2);
 
 
 
 
 // Get relative domain parameters to be displayed on Vignette 2
 $result_rel = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Percentile_2, Hours_Worked_Percentile_2, BMI_Percentile_2, Pain_Percentile_2, Phys_Percentile_2, NumFrds_Percentile_2, FreqFrds_Percentile_2, NumOrg_Percentile_2, Unemployment_Rate_2, Partner_Val_2, Trust_Val_2, Name2, Gender2", $_POST['ID']);  
 
 $row_rel = mysqli_fetch_assoc($result_rel);
 
 
 $income_Per2 = format_number_significant_figures($row_rel['HouseHold_Income_Percentile_2'],1);
 $hoursWorked_Per2 = format_number_significant_figures($row_rel['Hours_Worked_Percentile_2'],1);
 $BMI_Per2 = format_number_significant_figures($row_rel['BMI_Percentile_2'],1);
 $pain_Per2 = format_number_significant_figures($row_rel['Pain_Percentile_2'],1);
 $phys_Per2 = format_number_significant_figures($row_rel['Phys_Percentile_2'],1);
 $numFrds_Per2 = format_number_significant_figures($row_rel['NumFrds_Percentile_2'],1);
 $freqFrds_Per2 = format_number_significant_figures($row_rel['FreqFrds_Percentile_2'],1);
 $numOrg_Per2 = format_number_significant_figures($row_rel['NumOrg_Percentile_2'],1);
 $unemploy_Val2 = format_number_significant_figures($row_rel['Unemployment_Rate_2'],1);
 $partner_Val2 = format_number_significant_figures($row_rel['Partner_Val_2'],1);
 $alone2 = 100- $partner_Val2;
 $trust_Val2 = format_number_significant_figures($row_rel['Trust_Val_2'],1); 
 $Name2 = $row_rel['Name2'];
 
 $Gender2 = $row_rel['Gender2'];
 
 $GenderPronoun2 = '';
 
 if($Gender2 == 'Male')
 {
	 $GenderPronoun2 = 'his';
     $GenderNoun2 = 'he';	 
 }
 else if ($Gender2 == 'Female')
 {
     $GenderPronoun2= 'her';
	 $GenderNoun2 = 'she';
 }
 

 
 
 
  
  
/* Display Vignette 2 Form */
 include_once('vignette2Markup.php'); 


?>
