<?php


/* A. Prompts for the Survey and Vignettes
 * 
 * Based on the language selected in the new_welcome page, the appropiate
 * texts for survey and vignette prompts from dictionaries.php is used
 */ 
$prompts = $Survey_Prompts_Displayed; // survey prompts to be displayed
$vig_prompts = $Vignette_Prompts_Displayed;   // prompts specific to Vignettes


/* B. Vignettes Text
 * 
 * The texts for the vignettes are generated by an algorithm in "generate.py"
 * The generated text is passed from python to mysql. (Consider using json to get text as an array in php from Python?)
 * This section will read the Vignette text from mysql database
 *  
 * Workflow: PYTHON (generate.py) ----generated text ----> MYSQL DATABASE ----generated text----> PHP (showVignetteX.php)
 */
 
 $result_order = sqlRowSelect('USA_vignettes_order_2017', "vig1LabourName1, vig1LabourID1, vig1LabourName2, vig1LabourID2, vig1HealthName1, vig1HealthID1, vig1HealthName2, vig1HealthID2, vig1HealthName3, vig1HealthID3, vig1SocialName1, vig1SocialID1, vig1SocialName2, vig1SocialID2, vig1SocialName3, vig1SocialID3, vig1SocialName4, vig1SocialID4, vig1SocialName5, vig1SocialID5, vig1CatOrder1, vig1CatOrder2, vig1CatOrder3", $_POST['ID']);      
 $row_order = mysqli_fetch_assoc($result_order);
 
 
 $result_text = sqlRowSelect('USA_vignettes_2017', "Vignette5Text, Vignette4Text, Vignette3Text, Vignette2Text, Vignette1Text, Vignette1TextLabour, Vignette1TextHealth, Vignette1TextSoc, Partner_Bool_1, Trust_Bool_1", $_POST['ID']);      
 $row_text = mysqli_fetch_assoc($result_text);
 
 
 
 $result_ans = sqlRowSelect('USA_responses_2017', "Vignette5Answer, Vignette4Answer, Vignette3Answer, Vignette2Answer, Vignette1Answer", $_POST['ID']);  
 $row_ans = mysqli_fetch_assoc($result_ans);
 
 
 
 // Full Vignette text
 $Vignette5Displayed= $row_text['Vignette5Text'];  //read Vignette 5 Text from mysql database
 $Vignette4Displayed= $row_text['Vignette4Text'];  //read Vignette 4 Text from mysql database
 $Vignette3Displayed= $row_text['Vignette3Text'];  //read Vignette 3 Text from mysql database
 $Vignette2Displayed= $row_text['Vignette2Text'];  //read Vignette 2 Text from mysql database
 $Vignette1Displayed= $row_text['Vignette1Text'];  //read Vignette 1 Text from mysql database
 
 // Vignette 1 Text by domain and order
 $Vignette1TextLabour = $row_text['Vignette1TextLabour'];
 $Vignette1TextHealth = $row_text['Vignette1TextHealth'];
 $Vignette1TextSoc = $row_text['Vignette1TextSoc'];
 
 
 $vig1CatOrder1 = $row_order['vig1CatOrder1'];
 $vig1CatOrder2 = $row_order['vig1CatOrder2'];
 $vig1CatOrder3 = $row_order['vig1CatOrder3'];
 
 $vig1Order = array($vig1CatOrder1, $vig1CatOrder2, $vig1CatOrder3);
 
 $vig1LabourName1 = $row_order['vig1LabourName1'];
 $vig1LabourID1 = $row_order['vig1LabourID1'];
 $vig1LabourName2 = $row_order['vig1LabourName2'];
 $vig1LabourID2 = $row_order['vig1LabourID2'];
 $vig1HealthName1 = $row_order['vig1HealthName1'];
 $vig1HealthID1 = $row_order['vig1HealthID1'];
 $vig1HealthName2 = $row_order['vig1HealthName2'];
 $vig1HealthID2 = $row_order['vig1HealthID2'];
 $vig1HealthName3 = $row_order['vig1HealthName3'];
 $vig1HealthID3 = $row_order['vig1HealthID3'];
 $vig1SocialName1 = $row_order['vig1SocialName1'];
 $vig1SocialID1 = $row_order['vig1SocialID1'];
 $vig1SocialName2 = $row_order['vig1SocialName2'];
 $vig1SocialID2 = $row_order['vig1SocialID2'];
 $vig1SocialName3 = $row_order['vig1SocialName3'];
 $vig1SocialID3 = $row_order['vig1SocialID3'];
 $vig1SocialName4 = $row_order['vig1SocialName4'];
 $vig1SocialID4 = $row_order['vig1SocialID4'];
 $vig1SocialName5 = $row_order['vig1SocialName5'];
 $vig1SocialID5 = $row_order['vig1SocialID5'];
 
 
 
 
 
 // Boolean for living with partner and reported trust
 $vig1PartnerBool = $row_text['Partner_Bool_1'];
 $vig1TrustBool = $row_text['Trust_Bool_1'];




//Vignette Response
 $vignette5Answer= $row_ans['Vignette5Answer'];  //read Vignette 5 Answer from mysql database
 $vignette4Answer= $row_ans['Vignette4Answer'];  //read Vignette 4 Answer from mysql database
 $vignette3Answer= $row_ans['Vignette3Answer'];  //read Vignette 3 Answer from mysql database
 $vignette2Answer= $row_ans['Vignette2Answer'];  //read Vignette 2 Answer from mysql database
 $vignette1Answer= $row_ans['Vignette1Answer'];  //read Vignette 1 Answer from mysql database
 
 
 // Get abs domain parameters to be displayed on Vignette 1
 $result_abs = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Val_1, Hours_Worked_Val_1, BMI_Val_1, BMI_Cat_1, Pain_Cat_1, Phys_Cat_1, Phys_Val_1, NumFrds_Val_1, FreqFrds_Cat_1, NumOrg_Val_1", $_POST['ID']);  
 
 $row_abs = mysqli_fetch_assoc($result_abs);
 
 $income_Val1 = number_format($row_abs['HouseHold_Income_Val_1']);
 $hoursWorked_Val1 = round($row_abs['Hours_Worked_Val_1']);
 $BMI_Val1 = round($row_abs['BMI_Val_1']);
 $BMI_Cat1 = $row_abs['BMI_Cat_1'];
 $pain_Cat1 = $row_abs['Pain_Cat_1'];
 $phys_Cat1 = $row_abs['Phys_Cat_1'];
 $phys_Val1 = round($row_abs['Phys_Val_1']);
 $numFrds_Val1 = round($row_abs['NumFrds_Val_1']);
 $freqFrds_Cat1 = $row_abs['FreqFrds_Cat_1'];
 $numOrg_Val1 = round($row_abs['NumOrg_Val_1']);
 
 $strFreqFrdRarely = "rarely and did not make any contact in the past month";
 $freqFrds_Val1 = strcmp($strFreqFrdRarely, $freqFrds_Cat1);
 
 
 

 // Get relative domain parameters to be displayed on Vignette 1
 $result_rel = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Percentile_1, Hours_Worked_Percentile_1, BMI_Percentile_1, Pain_Percentile_1, Phys_Percentile_1, NumFrds_Percentile_1, FreqFrds_Percentile_1, NumOrg_Percentile_1, Unemployment_Rate_1, Partner_Val_1, Trust_Val_1, Name1, Gender1", $_POST['ID']);  
 
 $row_rel = mysqli_fetch_assoc($result_rel);
 
 
 $income_Per1 = format_number_significant_figures($row_rel['HouseHold_Income_Percentile_1'],1);
 $hoursWorked_Per1 = format_number_significant_figures($row_rel['Hours_Worked_Percentile_1'],1);
 $BMI_Per1 = format_number_significant_figures($row_rel['BMI_Percentile_1'],1);
 $pain_Per1 = format_number_significant_figures($row_rel['Pain_Percentile_1'],1);
 $phys_Per1 = format_number_significant_figures($row_rel['Phys_Percentile_1'],1);
 $numFrds_Per1 = format_number_significant_figures($row_rel['NumFrds_Percentile_1'],1);
 $freqFrds_Per1 = format_number_significant_figures($row_rel['FreqFrds_Percentile_1'],1);
 $numOrg_Per1 = format_number_significant_figures($row_rel['NumOrg_Percentile_1'],1);
 $unemploy_Val1 = format_number_significant_figures($row_rel['Unemployment_Rate_1'],1);
 $partner_Val1 = format_number_significant_figures($row_rel['Partner_Val_1'],1);
 $alone1 = 100- $partner_Val1;
 $trust_Val1 = format_number_significant_figures($row_rel['Trust_Val_1'],1); 
 $Name1 = $row_rel['Name1'];
 
 $Gender1 = $row_rel['Gender1'];
 
 $GenderPronoun1 = '';
 
 if($Gender1 == 'Male')
 {
	 $GenderPronoun1 = 'his';
	 $GenderNoun1 = 'he';	
 }
 
 else if ($Gender1 == 'Female')
 {
     $GenderPronoun1 = 'her';
     $GenderNoun1 = 'she';
     
 }
 
 /* Vignette 1 Form */
include_once('vignette1Markup.php'); //Vignette 1 form



?>
