<?php



/* A. Prompts for the Survey and Vignettes
 * 
 * Based on the language selected in the new_welcome page, the appropiate
 * texts for survey and vignette prompts from dictionaries.php is used
 */ 
$prompts = $Survey_Prompts_Displayed; // survey prompts to be displayed
$vig_prompts = $Vignette_Prompts_Displayed;   // prompts specific to Vignettes



/* B. Vignettes Text
 * 
 * The texts for the vignettes are generated by an algorithm in "generate.py"
 * The generated text is passed from python to mysql. (Consider using json to get text as an array in php from Python?)
 * This section will read the Vignette text from mysql database
 *
 * Also read the vignette text and responses from all previous Vignettes.  
 * These will be optional displays for the users.
 *   
 * Workflow: PYTHON (generate.py) ----generated text ----> MYSQL DATABASE ----generated text----> PHP (showVignetteX.php)
 */
 
 
 
 $result_order = sqlRowSelect('USA_vignettes_order_2017', "vig3LabourName1, vig3LabourID1, vig3LabourName2, vig3LabourID2, vig3HealthName1, vig3HealthID1, vig3HealthName2, vig3HealthID2, vig3HealthName3, vig3HealthID3, vig3SocialName1, vig3SocialID1, vig3SocialName2, vig3SocialID2, vig3SocialName3, vig3SocialID3, vig3SocialName4, vig3SocialID4, vig3SocialName5, vig3SocialID5, vig3CatOrder1, vig3CatOrder2, vig3CatOrder3", $_POST['ID']);      
 $row_order = mysqli_fetch_assoc($result_order);
 
 
 
 $result_text = sqlRowSelect('USA_vignettes_2017', "Vignette5Text, Vignette4Text, Vignette3Text, Vignette2Text, Vignette1Text, Vignette3TextLabour, Vignette3TextHealth, Vignette3TextSoc, Partner_Bool_3, Trust_Bool_3", $_POST['ID']);      
 $row_text = mysqli_fetch_assoc($result_text);
 
 
 $result_ans = sqlRowSelect('USA_responses_2017', "Vignette5Answer, Vignette4Answer, Vignette3Answer, Vignette2Answer, Vignette1Answer", $_POST['ID']);  
 $row_ans = mysqli_fetch_assoc($result_ans);
 
 
 
 // Full Vignette text
 $Vignette5Displayed= $row_text['Vignette5Text'];  //read Vignette 5 Text from mysql database
 $Vignette4Displayed= $row_text['Vignette4Text'];  //read Vignette 4 Text from mysql database
 $Vignette3Displayed= $row_text['Vignette3Text'];  //read Vignette 3 Text from mysql database
 $Vignette2Displayed= $row_text['Vignette2Text'];  //read Vignette 2 Text from mysql database
 $Vignette1Displayed= $row_text['Vignette1Text'];  //read Vignette 1 Text from mysql database
 
 // Vignette 3 Text by domain and order
 $Vignette3TextLabour = $row_text['Vignette3TextLabour'];
 $Vignette3TextHealth = $row_text['Vignette3TextHealth'];
 $Vignette3TextSoc = $row_text['Vignette3TextSoc'];
 
 
 $vig3CatOrder1 = $row_order['vig3CatOrder1'];
 $vig3CatOrder2 = $row_order['vig3CatOrder2'];
 $vig3CatOrder3 = $row_order['vig3CatOrder3'];
 
 $vig3Order = array($vig3CatOrder1, $vig3CatOrder2, $vig3CatOrder3);
 
 $vig3LabourName1 = $row_order['vig3LabourName1'];
 $vig3LabourID1 = $row_order['vig3LabourID1'];
 $vig3LabourName2 = $row_order['vig3LabourName2'];
 $vig3LabourID2 = $row_order['vig3LabourID2'];
 $vig3HealthName1 = $row_order['vig3HealthName1'];
 $vig3HealthID1 = $row_order['vig3HealthID1'];
 $vig3HealthName2 = $row_order['vig3HealthName2'];
 $vig3HealthID2 = $row_order['vig3HealthID2'];
 $vig3HealthName3 = $row_order['vig3HealthName3'];
 $vig3HealthID3 = $row_order['vig3HealthID3'];
 $vig3SocialName1 = $row_order['vig3SocialName1'];
 $vig3SocialID1 = $row_order['vig3SocialID1'];
 $vig3SocialName2 = $row_order['vig3SocialName2'];
 $vig3SocialID2 = $row_order['vig3SocialID2'];
 $vig3SocialName3 = $row_order['vig3SocialName3'];
 $vig3SocialID3 = $row_order['vig3SocialID3'];
 $vig3SocialName4 = $row_order['vig3SocialName4'];
 $vig3SocialID4 = $row_order['vig3SocialID4'];
 $vig3SocialName5 = $row_order['vig3SocialName5'];
 $vig3SocialID5 = $row_order['vig3SocialID5'];
 
 
 
 
 // Boolean for living with partner/trust
 $vig3PartnerBool = $row_text['Partner_Bool_3'];
 $vig3TrustBool = $row_text['Trust_Bool_3'];

//Vignette Response
 $vignette5Answer= $row_ans['Vignette5Answer'];  //read Vignette 5 Answer from mysql database
 $vignette4Answer= $row_ans['Vignette4Answer'];  //read Vignette 4 Answer from mysql database
 $vignette3Answer= $row_ans['Vignette3Answer'];  //read Vignette 3 Answer from mysql database
 $vignette2Answer= $row_ans['Vignette2Answer'];  //read Vignette 2 Answer from mysql database
 $vignette1Answer= $row_ans['Vignette1Answer'];  //read Vignette 1 Answer from mysql database
 
 
 
 // Get abs domain parameters to be displayed on Vignette 3
 $result_abs = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Val_3, Hours_Worked_Val_3, BMI_Val_3, BMI_Cat_3, Pain_Cat_3, Phys_Cat_3, Phys_Val_3, NumFrds_Val_3, FreqFrds_Cat_3, NumOrg_Val_3", $_POST['ID']);  
 
 $row_abs = mysqli_fetch_assoc($result_abs);
 
 $income_Val3 = number_format($row_abs['HouseHold_Income_Val_3']);
 $hoursWorked_Val3 = round($row_abs['Hours_Worked_Val_3']);
 $BMI_Val3 = round($row_abs['BMI_Val_3']);
 $BMI_Cat3 = $row_abs['BMI_Cat_3'];
 $pain_Cat3 = $row_abs['Pain_Cat_3'];
 $phys_Cat3 = $row_abs['Phys_Cat_3'];
 $phys_Val3 = round($row_abs['Phys_Val_3']);
 $numFrds_Val3 = round($row_abs['NumFrds_Val_3']);
 $freqFrds_Cat3 = $row_abs['FreqFrds_Cat_3'];
 $numOrg_Val3 = round($row_abs['NumOrg_Val_3']);
 
 $strFreqFrdRarely = "rarely and did not make any contact in the past month";
 $freqFrds_Val3 = strcmp($strFreqFrdRarely, $freqFrds_Cat3);
 

 
 
 // Get relative domain parameters to be displayed on Vignette 3
 $result_rel = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Percentile_3, Hours_Worked_Percentile_3, BMI_Percentile_3, Pain_Percentile_3, Phys_Percentile_3, NumFrds_Percentile_3, FreqFrds_Percentile_3, NumOrg_Percentile_3, Unemployment_Rate_3, Partner_Val_3, Trust_Val_3, Name3, Gender3", $_POST['ID']);  
 
 $row_rel = mysqli_fetch_assoc($result_rel);
 
 
 $income_Per3 = format_number_significant_figures($row_rel['HouseHold_Income_Percentile_3'],1);
 $hoursWorked_Per3 = format_number_significant_figures($row_rel['Hours_Worked_Percentile_3'],1);
 $BMI_Per3 = format_number_significant_figures($row_rel['BMI_Percentile_3'],1);
 $pain_Per3 = format_number_significant_figures($row_rel['Pain_Percentile_3'],1);
 $phys_Per3 = format_number_significant_figures($row_rel['Phys_Percentile_3'],1);
 $numFrds_Per3 = format_number_significant_figures($row_rel['NumFrds_Percentile_3'],1);
 $freqFrds_Per3 = format_number_significant_figures($row_rel['FreqFrds_Percentile_3'],1);
 $numOrg_Per3 = format_number_significant_figures($row_rel['NumOrg_Percentile_3'],1);
 $unemploy_Val3 = format_number_significant_figures($row_rel['Unemployment_Rate_3'],1);
 $partner_Val3 = format_number_significant_figures($row_rel['Partner_Val_3'],1);
 $alone3 = 100- $partner_Val3;
 $trust_Val3 = format_number_significant_figures($row_rel['Trust_Val_3'],1); 
 $Name3 = $row_rel['Name3'];
 
 $Gender3 = $row_rel['Gender3'];
 
 $GenderPronoun3 = '';
 
 if($Gender3 == 'Male')
 {
	 $GenderPronoun3 = 'his';
	 $GenderNoun3 = 'he';
 }
 else if ($Gender3 == 'Female')
 {
     $GenderPronoun3= 'her';
	 $GenderNoun3 = 'she';
 }
  
 
/* Display Vignette 3 Form */
 include_once('vignette3Markup.php'); 



?>
