
# Data Files
data_file: data.csv
dict_file: data_dict.csv

# LCA cluster variables

proto_cluster:
  pouch: pouch_ratenw
  box: box_ratenw
  sachet: sachet_ratenw
  merm: merm_ratenw


clustering_inputs:
  pouch:
    - storage_capcity
    - storage_othmedic
    - internal_compaart
    - prescript_card
    - weight_comfort
    - comfrt_publ
    - pouch_dailyTravel
    - pouch_rightsize
    - pouch_effort
    - pouch_apearance
    - pouch_security

  box:
    - hingestorage_capcity
    - slidingstorage_capcity
    - boxweight_comfort
    - boxcomfrt_publ
    - box_dailyTravel
    - box_rightsize
    - box_effort
    - box_apearance
    - box_security
  
  sachet:
    - sachet_storage_capcity
    - sachet_dailyTravel
    - sachet_comfrt_publ
    - sachet_rightsize
    - sachet_apearance
    - sachet_security
    - sachet_refill

  merm:
    - merm_storage_capcity
    - merm_storage_othmedic
    - merm_weight_comfort
    - merm_dailyTravel
    - merm_comfrt_publ
    - merm_rightsize
    - merm_effort
    - merm_apearance
    - merm_security

prototypes:
  - pouch
  - box
  - sachet
  - merm


selected_features:
  - gender

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

# decision tree parameters
pouch_dt_params:
  min_samples_leaf: 1
  pruning_level: 0.0

box_dt_params:
  min_samples_leaf: 3
  pruning_level: 0.02

sachet_dt_params:
  min_samples_leaf: 1
  pruning_level: 0.0

merm_dt_params:
  min_samples_leaf: 4
  pruning_level: 0.0


# number of the top most important features for the classifier to display
num_feature_importance: 5

