# Package Overview
PACKAGE_NAME: banglore_home_prices_model

# Data Files
RAW_DATA_FILE: house_prices.csv
TEST_DATA_FILE: test_data.csv

# pipeline saved file name
SAVED_PIPELINE_FILENAME: home_prices_pipeline_xgb_v

# comparision plot (model performance)
MODEL_PERF_PLOT_NAME: plot_baseline_vs_xgb_v

# Variables
OUTCOME_VARIABLE: price

# selected features
FEATURES:
  - area_type
  - availability
  - size
  - total_sqft
  - bath
  - location

# set train/test split
TEST_SIZE: 0.2

# to set the random seed
RANDOM_STATE: 10

# data processing parameters
AREA_TYPE_RETAIN: 2
SQFT_PER_SQ_METER: 10.764
SQFT_PER_SQ_YARD: 9.0 

VARS_MISSING_IMPUTED:
  - bath

VARS_WITH_NA_MISSING:
  - bath
  - size

# Nominal variables
NOMINAL_VARS:
  - area_type
  - availability
  - location

# Continuous variables
CONTINUOUS_VARS:
  - size
  - total_sqft
  - bath

# model hyperparameters
COLSAMPLE_BYTREE: 0.6
MAX_DEPTH: 20
SUBSAMPLE: 1.0
N_ESTIMATORS: 500
GAMMA: 0.05
LEARNING_RATE: 0.05

