<?php


/* A. Prompts for the Survey and Vignettes
 * 
 * Based on the language selected in the new_welcome page, the appropiate
 * texts for survey and vignette prompts from dictionaries.php is used
 */ 
$prompts = $Survey_Prompts_Displayed; // survey prompts to be displayed
$vig_prompts = $Vignette_Prompts_Displayed;   // prompts specific to Vignettes



/* B. Vignettes Text
 * 
 * The texts for the vignettes are generated by an algorithm in "generate.py"
 * The generated text is passed from python to mysql. 
 * This section will read the Vignette text from mysql database
 *
 * Read the vignette text and responses from all previous Vignettes.  
 * These will be optional displays for the users.
 * 
 * Read the time duration of Vignettes 1-3. This will be used to determined if the user is eligible for a bonus
 *   
 * Workflow: PYTHON (generate.py) ----generated text ----> MYSQL DATABASE ----generated text----> PHP (showVignetteX.php)
 */
 
 $result_order = sqlRowSelect('USA_vignettes_order_2017', "vig4LabourName1, vig4LabourID1, vig4LabourName2, vig4LabourID2, vig4HealthName1, vig4HealthID1, vig4HealthName2, vig4HealthID2, vig4HealthName3, vig4HealthID3, vig4SocialName1, vig4SocialID1, vig4SocialName2, vig4SocialID2, vig4SocialName3, vig4SocialID3, vig4SocialName4, vig4SocialID4, vig4SocialName5, vig4SocialID5, vig4CatOrder1, vig4CatOrder2, vig4CatOrder3", $_POST['ID']);      
 $row_order = mysqli_fetch_assoc($result_order);
 
 
 $result_text = sqlRowSelect('USA_vignettes_2017', "Vignette5Text, Vignette4Text, Vignette3Text, Vignette2Text, Vignette1Text, Vignette4TextLabour, Vignette4TextHealth, Vignette4TextSoc, Partner_Bool_4, Trust_Bool_4", $_POST['ID']);      
 $row_text = mysqli_fetch_assoc($result_text);
 
 
 $result_ans = sqlRowSelect('USA_responses_2017', "Vignette5Answer, Vignette4Answer, Vignette3Answer, Vignette2Answer, Vignette1Answer, V3TimeLength, V2TimeLength, V1TimeLength", $_POST['ID']);  
 $row_ans = mysqli_fetch_assoc($result_ans);
 
 
 
 // Full Vignette text
 $Vignette5Displayed= $row_text['Vignette5Text'];  //read Vignette 5 Text from mysql database
 $Vignette4Displayed= $row_text['Vignette4Text'];  //read Vignette 4 Text from mysql database
 $Vignette3Displayed= $row_text['Vignette3Text'];  //read Vignette 3 Text from mysql database
 $Vignette2Displayed= $row_text['Vignette2Text'];  //read Vignette 2 Text from mysql database
 $Vignette1Displayed= $row_text['Vignette1Text'];  //read Vignette 1 Text from mysql database
 
 // Vignette 4 Text by domain and order
 $Vignette4TextLabour = $row_text['Vignette4TextLabour'];
 $Vignette4TextHealth = $row_text['Vignette4TextHealth'];
 $Vignette4TextSoc = $row_text['Vignette4TextSoc'];
 
 
 $vig4CatOrder1 = $row_order['vig4CatOrder1'];
 $vig4CatOrder2 = $row_order['vig4CatOrder2'];
 $vig4CatOrder3 = $row_order['vig4CatOrder3'];
 
 $vig4Order = array($vig4CatOrder1, $vig4CatOrder2, $vig4CatOrder3);
 
 $vig4LabourName1 = $row_order['vig4LabourName1'];
 $vig4LabourID1 = $row_order['vig4LabourID1'];
 $vig4LabourName2 = $row_order['vig4LabourName2'];
 $vig4LabourID2 = $row_order['vig4LabourID2'];
 $vig4HealthName1 = $row_order['vig4HealthName1'];
 $vig4HealthID1 = $row_order['vig4HealthID1'];
 $vig4HealthName2 = $row_order['vig4HealthName2'];
 $vig4HealthID2 = $row_order['vig4HealthID2'];
 $vig4HealthName3 = $row_order['vig4HealthName3'];
 $vig4HealthID3 = $row_order['vig4HealthID3'];
 $vig4SocialName1 = $row_order['vig4SocialName1'];
 $vig4SocialID1 = $row_order['vig4SocialID1'];
 $vig4SocialName2 = $row_order['vig4SocialName2'];
 $vig4SocialID2 = $row_order['vig4SocialID2'];
 $vig4SocialName3 = $row_order['vig4SocialName3'];
 $vig4SocialID3 = $row_order['vig4SocialID3'];
 $vig4SocialName4 = $row_order['vig4SocialName4'];
 $vig4SocialID4 = $row_order['vig4SocialID4'];
 $vig4SocialName5 = $row_order['vig4SocialName5'];
 $vig4SocialID5 = $row_order['vig4SocialID5'];
 
 
 
 
 // Boolean for living with partner/trust
 $vig4PartnerBool = $row_text['Partner_Bool_4'];
 $vig4TrustBool = $row_text['Trust_Bool_4'];


//Vignette Response
 $vignette5Answer= $row_ans['Vignette5Answer'];  //read Vignette 5 Answer from mysql database
 $vignette4Answer= $row_ans['Vignette4Answer'];  //read Vignette 4 Answer from mysql database
 $vignette3Answer= $row_ans['Vignette3Answer'];  //read Vignette 3 Answer from mysql database
 $vignette2Answer= $row_ans['Vignette2Answer'];  //read Vignette 2 Answer from mysql database
 $vignette1Answer= $row_ans['Vignette1Answer'];  //read Vignette 1 Answer from mysql database
 
 //Vignette Duration
 $vignette3TimeDur = $row_ans['V3TimeLength'];  //read Vignette 3 Time Duration from mysql database
 $vignette2TimeDur = $row_ans['V2TimeLength'];  //read Vignette 2 Time Duration from mysql database
 $vignette1TimeDur = $row_ans['V1TimeLength'];  //read Vignette 1 Time Duration from mysql database
 
 
 // Get abs domain parameters to be displayed on Vignette 4
 $result_abs = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Val_4, Hours_Worked_Val_4, BMI_Val_4, BMI_Cat_4, Pain_Cat_4, Phys_Cat_4, Phys_Val_4, NumFrds_Val_4, FreqFrds_Cat_4, NumOrg_Val_4", $_POST['ID']);  
 
 $row_abs = mysqli_fetch_assoc($result_abs);
 
 $income_Val4 = number_format($row_abs['HouseHold_Income_Val_4']);
 $hoursWorked_Val4 = round($row_abs['Hours_Worked_Val_4']);
 $BMI_Val4 = round($row_abs['BMI_Val_4']);
 $BMI_Cat4 = $row_abs['BMI_Cat_4'];
 $pain_Cat4 = $row_abs['Pain_Cat_4'];
 $phys_Cat4 = $row_abs['Phys_Cat_4'];
 $phys_Val4 = round($row_abs['Phys_Val_4']);
 $numFrds_Val4 = round($row_abs['NumFrds_Val_4']);
 $freqFrds_Cat4 = $row_abs['FreqFrds_Cat_4'];
 $numOrg_Val4 = round($row_abs['NumOrg_Val_4']);
 
 $strFreqFrdRarely = "rarely and did not make any contact in the past month";
 $freqFrds_Val4 = strcmp($strFreqFrdRarely, $freqFrds_Cat4);
 
 
 
 
 
 
 
 // Get relative domain parameters to be displayed on Vignette 4
 $result_rel = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Percentile_4, Hours_Worked_Percentile_4, BMI_Percentile_4, Pain_Percentile_4, Phys_Percentile_4, NumFrds_Percentile_4, FreqFrds_Percentile_4, NumOrg_Percentile_4, Unemployment_Rate_4, Partner_Val_4, Trust_Val_4, Name4, Gender4", $_POST['ID']);  
 
 $row_rel = mysqli_fetch_assoc($result_rel);
 
 
 $income_Per4 = format_number_significant_figures($row_rel['HouseHold_Income_Percentile_4'],1);
 $hoursWorked_Per4 = format_number_significant_figures($row_rel['Hours_Worked_Percentile_4'],1);
 $BMI_Per4 = format_number_significant_figures($row_rel['BMI_Percentile_4'],1);
 $pain_Per4 = format_number_significant_figures($row_rel['Pain_Percentile_4'],1);
 $phys_Per4 = format_number_significant_figures($row_rel['Phys_Percentile_4'],1);
 $numFrds_Per4 = format_number_significant_figures($row_rel['NumFrds_Percentile_4'],1);
 $freqFrds_Per4 = format_number_significant_figures($row_rel['FreqFrds_Percentile_4'],1);
 $numOrg_Per4 = format_number_significant_figures($row_rel['NumOrg_Percentile_4'],1);
 $unemploy_Val4 = format_number_significant_figures($row_rel['Unemployment_Rate_4'],1);
 $partner_Val4 = format_number_significant_figures($row_rel['Partner_Val_4'],1);
 $alone4 = 100- $partner_Val4;
 $trust_Val4 = format_number_significant_figures($row_rel['Trust_Val_4'],1); 
 $Name4 = $row_rel['Name4'];
 
 $Gender4 = $row_rel['Gender4'];
 
 $GenderPronoun4 = '';
 
 if($Gender4 == 'Male')
 {
	 $GenderPronoun4 = 'his';
     $GenderNoun4 = 'he';	 
 }
 else if ($Gender4 == 'Female')
 {
     $GenderPronoun4 = 'her';
	 $GenderNoun4 = 'she';
 }
  

/* Check if the user is eligible for a bonus based on the amount of time he/she spends in Vignettes 1-3. */
 include_once('checkBonusEligible.php');


/* Display Vignette 4 Form */ 
 include_once('vignette4Markup.php'); 


?>
