<?php


/* A. Prompts for the Survey and Vignettes
 * 
 * Based on the language selected in the new_welcome page, the appropiate
 * texts for survey and vignette prompts from dictionaries.php is used
 */ 
$prompts = $Survey_Prompts_Displayed; // survey prompts to be displayed
$vig_prompts = $Vignette_Prompts_Displayed;   // prompts specific to Vignettes




/* B. Vignettes Text
 * 
 * The texts for the vignettes are generated by an algorithm in "generate.py"
 * The generated text is passed from python to mysql. (Consider using json to get text as an array in php from Python?)
 * This section will read the Vignette text from mysql database
 *
 * Read the vignette text and responses from all previous Vignettes.  
 * These will be optional displays for the users.
 *   
 * Workflow: PYTHON (generate.py) ----generated text ----> MYSQL DATABASE ----generated text----> PHP (showVignetteX.php)
 */
 
 
 $result_order = sqlRowSelect('USA_vignettes_order_2017', "vig5LabourName1, vig5LabourID1, vig5LabourName2, vig5LabourID2, vig5HealthName1, vig5HealthID1, vig5HealthName2, vig5HealthID2, vig5HealthName3, vig5HealthID3, vig5SocialName1, vig5SocialID1, vig5SocialName2, vig5SocialID2, vig5SocialName3, vig5SocialID3, vig5SocialName4, vig5SocialID4, vig5SocialName5, vig5SocialID5, vig5CatOrder1, vig5CatOrder2, vig5CatOrder3", $_POST['ID']);      
 $row_order = mysqli_fetch_assoc($result_order);
 
 
 $result_text = sqlRowSelect('USA_vignettes_2017', "Vignette5Text, Vignette4Text, Vignette3Text, Vignette2Text, Vignette1Text, Vignette5TextLabour, Vignette5TextHealth, Vignette5TextSoc, Partner_Bool_5, Trust_Bool_5", $_POST['ID']);      
 $row_text = mysqli_fetch_assoc($result_text);
 
 
 $result_ans = sqlRowSelect('USA_responses_2017', "Vignette5Answer, Vignette4Answer, Vignette3Answer, Vignette2Answer, Vignette1Answer", $_POST['ID']);  
 $row_ans = mysqli_fetch_assoc($result_ans);
 
 
 
 // Full Vignette text
 $Vignette5Displayed= $row_text['Vignette5Text'];  //read Vignette 5 Text from mysql database
 $Vignette4Displayed= $row_text['Vignette4Text'];  //read Vignette 4 Text from mysql database
 $Vignette3Displayed= $row_text['Vignette3Text'];  //read Vignette 3 Text from mysql database
 $Vignette2Displayed= $row_text['Vignette2Text'];  //read Vignette 2 Text from mysql database
 $Vignette1Displayed= $row_text['Vignette1Text'];  //read Vignette 1 Text from mysql database
 
 // Vignette 5 Text by domain and order
 $Vignette5TextLabour = $row_text['Vignette5TextLabour'];
 $Vignette5TextHealth = $row_text['Vignette5TextHealth'];
 $Vignette5TextSoc = $row_text['Vignette5TextSoc'];
 
 
 $vig5CatOrder1 = $row_order['vig5CatOrder1'];
 $vig5CatOrder2 = $row_order['vig5CatOrder2'];
 $vig5CatOrder3 = $row_order['vig5CatOrder3'];
 
 $vig5Order = array($vig5CatOrder1, $vig5CatOrder2, $vig5CatOrder3);
 
 $vig5LabourName1 = $row_order['vig5LabourName1'];
 $vig5LabourID1 = $row_order['vig5LabourID1'];
 $vig5LabourName2 = $row_order['vig5LabourName2'];
 $vig5LabourID2 = $row_order['vig5LabourID2'];
 $vig5HealthName1 = $row_order['vig5HealthName1'];
 $vig5HealthID1 = $row_order['vig5HealthID1'];
 $vig5HealthName2 = $row_order['vig5HealthName2'];
 $vig5HealthID2 = $row_order['vig5HealthID2'];
 $vig5HealthName3 = $row_order['vig5HealthName3'];
 $vig5HealthID3 = $row_order['vig5HealthID3'];
 $vig5SocialName1 = $row_order['vig5SocialName1'];
 $vig5SocialID1 = $row_order['vig5SocialID1'];
 $vig5SocialName2 = $row_order['vig5SocialName2'];
 $vig5SocialID2 = $row_order['vig5SocialID2'];
 $vig5SocialName3 = $row_order['vig5SocialName3'];
 $vig5SocialID3 = $row_order['vig5SocialID3'];
 $vig5SocialName4 = $row_order['vig5SocialName4'];
 $vig5SocialID4 = $row_order['vig5SocialID4'];
 $vig5SocialName5 = $row_order['vig5SocialName5'];
 $vig5SocialID5 = $row_order['vig5SocialID5'];
 
 
 
 
 // Boolean for living with partner/trust
 $vig5PartnerBool = $row_text['Partner_Bool_5'];
 $vig5TrustBool = $row_text['Trust_Bool_5'];


//Vignette Response
 $vignette5Answer= $row_ans['Vignette5Answer'];  //read Vignette 5 Answer from mysql database
 $vignette4Answer= $row_ans['Vignette4Answer'];  //read Vignette 4 Answer from mysql database
 $vignette3Answer= $row_ans['Vignette3Answer'];  //read Vignette 3 Answer from mysql database
 $vignette2Answer= $row_ans['Vignette2Answer'];  //read Vignette 2 Answer from mysql database
 $vignette1Answer= $row_ans['Vignette1Answer'];  //read Vignette 1 Answer from mysql database
 
 
 
 // Get abs domain parameters to be displayed on Vignette 5
 $result_abs = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Val_5, Hours_Worked_Val_5, BMI_Val_5, BMI_Cat_5, Pain_Cat_5, Phys_Cat_5, Phys_Val_5, NumFrds_Val_5, FreqFrds_Cat_5, NumOrg_Val_5", $_POST['ID']);  
 
 $row_abs = mysqli_fetch_assoc($result_abs);
 
 $income_Val5 = number_format($row_abs['HouseHold_Income_Val_5']);
 $hoursWorked_Val5 = round($row_abs['Hours_Worked_Val_5']);
 $BMI_Val5 = round($row_abs['BMI_Val_5']);
 $BMI_Cat5 = $row_abs['BMI_Cat_5'];
 $pain_Cat5 = $row_abs['Pain_Cat_5'];
 $phys_Cat5 = $row_abs['Phys_Cat_5'];
 $phys_Val5 = round($row_abs['Phys_Val_5']);
 $numFrds_Val5 = round($row_abs['NumFrds_Val_5']);
 $freqFrds_Cat5 = $row_abs['FreqFrds_Cat_5'];
 $numOrg_Val5 = round($row_abs['NumOrg_Val_5']);
 
 $strFreqFrdRarely = "rarely and did not make any contact in the past month";
 $freqFrds_Val5 = strcmp($strFreqFrdRarely, $freqFrds_Cat5);
 
 
 
 
 
 // Get relative domain parameters to be displayed on Vignette 5
 $result_rel = sqlRowSelect('USA_vignettes_2017', "HouseHold_Income_Percentile_5, Hours_Worked_Percentile_5, BMI_Percentile_5, Pain_Percentile_5, Phys_Percentile_5, NumFrds_Percentile_5, FreqFrds_Percentile_5, NumOrg_Percentile_5, Unemployment_Rate_5, Partner_Val_5, Trust_Val_5, Name5, Gender5", $_POST['ID']);  
 
 $row_rel = mysqli_fetch_assoc($result_rel);
 
 
 $income_Per5 = format_number_significant_figures($row_rel['HouseHold_Income_Percentile_5'],1);
 $hoursWorked_Per5 = format_number_significant_figures($row_rel['Hours_Worked_Percentile_5'],1);
 $BMI_Per5 = format_number_significant_figures($row_rel['BMI_Percentile_5'],1);
 $pain_Per5 = format_number_significant_figures($row_rel['Pain_Percentile_5'],1);
 $phys_Per5 = format_number_significant_figures($row_rel['Phys_Percentile_5'],1);
 $numFrds_Per5 = format_number_significant_figures($row_rel['NumFrds_Percentile_5'],1);
 $freqFrds_Per5 = format_number_significant_figures($row_rel['FreqFrds_Percentile_5'],1);
 $numOrg_Per5 = format_number_significant_figures($row_rel['NumOrg_Percentile_5'],1);
 $unemploy_Val5 = format_number_significant_figures($row_rel['Unemployment_Rate_5'],1);
 $partner_Val5 = format_number_significant_figures($row_rel['Partner_Val_5'],1);
 $alone5 = 100- $partner_Val5;
 $trust_Val5 = format_number_significant_figures($row_rel['Trust_Val_5'],1); 
 $Name5 = $row_rel['Name5'];
 
 $Gender5 = $row_rel['Gender5'];
 
 $GenderPronoun5 = '';
 
 if($Gender5 == 'Male')
 {
	 $GenderPronoun5 = 'his';
     $GenderNoun5 = 'he';	 
 }
 else if ($Gender5 == 'Female')
 {
     $GenderPronoun5 = 'her';
	 $GenderNoun5 = 'she';
 }
  

/* Display Vignette 5 Form */ 
 include_once('vignette5Markup.php'); 



?>
