# Package Overview
package_name: survey_analysis

# Data Files
training_data_file: survey.csv

# Variables
target: annual_salary

# selected features
features:
  - age_category
  - industry
  - state
  - city
  - overall_experience
  - in_field_experience
  - education
  - gender
  - race

# set train/test split
TEST_SIZE: 0.1

# to set the random seed
RANDOM_STATE: 10

# optimal parameters for gradient boosted tree from GridSearchCV
learning_rate: 0.05
max_depth: 3
max_features: 0.3
n_estimators: 1000
subsample: 1.0

# Custom lower bound for outlier removal
OUTLIER_LWR_BOUND: 5000

# Variables that I retain the X most frequent level and lump the rest as "Other"
CAT_VARS_10_MOST_FREQ:
    - state
    - city
    - industry

CAT_VARS_2_MOST_FREQ:
  - gender

CAT_VARS_4_MOST_FREQ:
  - race


# impute missing values with "missing"
CATEGORICAL_VARS_WITH_NA_MISSING:
  - industry
  - state
  - city
  - education
  - gender
  - race

# ordinal variables to be recoded (strings to integer)
EXPERIENCE_VARS:
  - overall_experience
  - in_field_experience

AGE_VARS:
  - age_category


# nominal variables to be one-hot encoded
NOMINAL_VARIABLES:
  - industry
  - state
  - city
  - gender
  - race
  - education
